sudo: true

language: bash

services:
  - docker

env:
  global:
    - DEBIAN_FRONTEND="noninteractive"
    - DOCKERHUB_LIVE="taisun/vdi-rdp"

jobs:
  include:
    - stage: "Build Containers"
      name: "Build Ubuntu"
      before_install:
        - /bin/bash pre_install
      script: ./builder.sh ubuntu ubuntu/
    - script: ./builder.sh alpine alpine/
      before_install:
        - /bin/bash pre_install
      name: "Build Alpine"
