sudo: true

language: bash

services:
  - docker

env:
  global:
    - DEBIAN_FRONTEND="noninteractive"
    - DOCKERHUB_LIVE="taisun/vdi"

jobs:
  include:
    - stage: "Build Containers"
      name: "Build Bionic"
      before_install:
        - /bin/bash pre_install
      script: ./builder.sh ubuntu-bionic ubuntu/bionic/
    - script: ./builder.sh ubuntu-xenial ubuntu/xenial/
      before_install:
        - /bin/bash pre_install
      name: "Build Xenial"
